apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: final-prd-tommain-hpa
  namespace: final-backend
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-prd-tommain
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: final-prd-tomsignup-hpa
  namespace: final-backend
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-prd-tomsignup
  targetCPUUtilizationPercentage: 40

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: final-prd-tomlogin-hpa
  namespace: final-backend
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-prd-tomlogin
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: final-prd-tomlogout-hpa
  namespace: final-backend
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-prd-tomlogout
  targetCPUUtilizationPercentage: 40
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: final-prd-tomorder-hpa
  namespace: final-backend
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-prd-tomorder
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: final-prd-tombook-hpa
  namespace: final-backend
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-prd-tomreservation
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: final-prd-tomreservationinfo-hpa
  namespace: final-backend
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-prd-tomreservationinfo
  targetCPUUtilizationPercentage: 50
