apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-sign
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 1st-websign
  targetCPUUtilizationPercentage: 20
