apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  
   # 주석 부분에 nginx-ingress 컨트롤러의 정보를 저장을 시도해봤습니다. 
   # 하지만, nginx-ingress 컨트롤러의 동작에 영향을 끼치지 않아 완벽한 트러블슈팅에는 실패하였습니다.
   
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:

# nginx-Ingress 컨트롤러를 설치할 때 "nginx"라는 이름으로 설치됨.

  ingressClassName: nginx
  rules:
    - http:
        paths:
        
        # client가 sign.jsp 또는 order.jsp에 바로 접근할 수 있는 경우를 예방
        
            pathType: Prefix
            backend:
              service:
                name: web-svc
                port:
                  number: 80
                  
          # client가 /sign으로 시작하는 모든 요청 처리
          
          - path: /sign
            pathType: Prefix
            backend:
              service:
                name: websign-svc
                port:
                  number: 80
                  
           # client가 /sign으로 시작하는 모든 요청 처리
           
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: weborder-svc
                port:
                  number: 80
