apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 1st-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /usr/share/nginx/html/1st-web
        pathType: Prefix
        backend:
          service:
            name: web-svc
            port:
              number: 80
      paths:
      - path: /usr/local/tomcat/webapps/ROOT/1st-was
        pathType: Prefix
        backend:
           service:
             name: was-svc
             port:
               number: 8080
