apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvweb
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: web-sc
  hostPath:
    path: /data/web
    type: DirectoryOrCreate

---

# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcweb
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: web-sc
