# 규칙: 주석은 아래 내용 부연설명, 짧은 내용은 옆에 추가
# hpa 파일 (파드 개수 조정하는 오토스케일링)
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-was
spec:
  # Pod 개수는 최소 3개부터 최대 10개까지 생성 가능 
  # (디플로이먼트에서 replicas 3개 설정했으므로)
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 1st-was
  # CPU 사용률이 50% 초과했을 때부터 오토스케일링 적용
  targetCPUUtilizationPercentage: 50
