apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was
spec:
  # 스토리지 용량: 8G
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  # 여러 개 pod에서 동시에 읽기/쓰기 접근 가능
  accessModes:
    - ReadWriteMany
  # Recycle: PV를 재사용할 때 데이터를 삭제하고 복구할 수 있는 정책
  persistentVolumeReclaimPolicy: Retain
  # PVC에서 이 PV를 요청할 때 사용될 스토리지 클래스
  storageClassName: was-sc
  hostPath:
    path: /data/was
    type: DirectoryOrCreate
---
apiVersion: v1
# PV에서 줬던 설정과 동일하게 작성
kind: PersistentVolumeClaim
metadata:
  name: pvc-was
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: was-sc


#기존에 hostPath부분이 deploy yaml파일에 작성되어있어서 PV.yaml 에 수정했습니다
